server:
  port: 10086 # 端口
spring:
  application:
    name: ly-register # 应用名称，会在Eureka中显示
eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true（此处因为自己就是server，所以不需要注册自己）
    fetch-registry: false # 是否拉取其它服务的信息，默认是true（此处因为自己就是server，所以不需要发现服务）
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka

